TTree count_tree("t_layers_energy","tree with energy deposited by 1GeV muon by layer");
Float_t layer_count[28] = {};
int fill_error = 0;
    
TBranch *b_layer_0 = count_tree.Branch("layer_0",&layer_count[0]);
TBranch *b_layer_1 = count_tree.Branch("layer_1",&layer_count[1]);
TBranch *b_layer_2 = count_tree.Branch("layer_2",&layer_count[2]);
TBranch *b_layer_3 = count_tree.Branch("layer_3",&layer_count[3]);
TBranch *b_layer_4 = count_tree.Branch("layer_4",&layer_count[4]);
TBranch *b_layer_5 = count_tree.Branch("layer_5",&layer_count[5]);
TBranch *b_layer_6 = count_tree.Branch("layer_6",&layer_count[6]);
TBranch *b_layer_7 = count_tree.Branch("layer_7",&layer_count[7]);
TBranch *b_layer_8 = count_tree.Branch("layer_8",&layer_count[8]);
TBranch *b_layer_9 = count_tree.Branch("layer_9",&layer_count[9]);
TBranch *b_layer_10 = count_tree.Branch("layer_10",&layer_count[10]);
TBranch *b_layer_11 = count_tree.Branch("layer_11",&layer_count[11]);
TBranch *b_layer_12 = count_tree.Branch("layer_12",&layer_count[12]);
TBranch *b_layer_13 = count_tree.Branch("layer_13",&layer_count[13]);
TBranch *b_layer_14 = count_tree.Branch("layer_14",&layer_count[14]);
TBranch *b_layer_15 = count_tree.Branch("layer_15",&layer_count[15]);
TBranch *b_layer_16 = count_tree.Branch("layer_16",&layer_count[16]);
TBranch *b_layer_17 = count_tree.Branch("layer_17",&layer_count[17]);
TBranch *b_layer_18 = count_tree.Branch("layer_18",&layer_count[18]);
TBranch *b_layer_19 = count_tree.Branch("layer_19",&layer_count[19]);
TBranch *b_layer_20 = count_tree.Branch("layer_20",&layer_count[20]);
TBranch *b_layer_21 = count_tree.Branch("layer_21",&layer_count[21]);
TBranch *b_layer_22 = count_tree.Branch("layer_22",&layer_count[22]);
TBranch *b_layer_23 = count_tree.Branch("layer_23",&layer_count[23]);
TBranch *b_layer_24 = count_tree.Branch("layer_24",&layer_count[24]);
TBranch *b_layer_25 = count_tree.Branch("layer_25",&layer_count[25]);
TBranch *b_layer_26 = count_tree.Branch("layer_26",&layer_count[26]);
TBranch *b_layer_27 = count_tree.Branch("layer_27",&layer_count[27]);

TBranch *b_layer_arr[28] = {b_layer_0,b_layer_1,b_layer_2,b_layer_3,b_layer_4,b_layer_5,b_layer_6,b_layer_7,b_layer_8,b_layer_9,b_layer_10,b_layer_11,b_layer_12,b_layer_13,b_layer_14,b_layer_15,b_layer_16,b_layer_17,b_layer_18,b_layer_19,b_layer_20,b_layer_21,b_layer_22,b_layer_23,b_layer_24,b_layer_25,b_layer_26,b_layer_27};
