 
sbatch shells_full_theta_vary/30_z_vals_file_0.sh
sbatch shells_full_theta_vary/30_z_vals_file_1.sh
sbatch shells_full_theta_vary/30_z_vals_file_2.sh
sbatch shells_full_theta_vary/30_z_vals_file_3.sh
sbatch shells_full_theta_vary/30_z_vals_file_4.sh
sbatch shells_full_theta_vary/30_z_vals_file_5.sh
sbatch shells_full_theta_vary/30_z_vals_file_6.sh
sbatch shells_full_theta_vary/30_z_vals_file_7.sh
sbatch shells_full_theta_vary/30_z_vals_file_8.sh
sbatch shells_full_theta_vary/30_z_vals_file_9.sh
sbatch shells_full_theta_vary/30_z_vals_file_10.sh
sbatch shells_full_theta_vary/30_z_vals_file_11.sh
sbatch shells_full_theta_vary/30_z_vals_file_12.sh
