 
sbatch shells/file_10.sh
sbatch shells/file_11.sh
sbatch shells/file_12.sh
sbatch shells/file_13.sh
sbatch shells/file_14.sh
sbatch shells/file_15.sh
sbatch shells/file_16.sh
sbatch shells/file_17.sh
sbatch shells/file_18.sh
sbatch shells/file_19.sh
sbatch shells/file_20.sh
sbatch shells/file_21.sh
sbatch shells/file_22.sh
sbatch shells/file_23.sh
sbatch shells/file_24.sh
sbatch shells/file_25.sh
sbatch shells/file_26.sh
sbatch shells/file_27.sh
sbatch shells/file_28.sh
sbatch shells/file_29.sh
sbatch shells/file_30.sh
