 
sbatch shells_full_theta_vary/file_0.sh
sbatch shells_full_theta_vary/file_1.sh
sbatch shells_full_theta_vary/file_2.sh
sbatch shells_full_theta_vary/file_3.sh
sbatch shells_full_theta_vary/file_4.sh
sbatch shells_full_theta_vary/file_5.sh
sbatch shells_full_theta_vary/file_6.sh
sbatch shells_full_theta_vary/file_7.sh
sbatch shells_full_theta_vary/file_8.sh
sbatch shells_full_theta_vary/file_9.sh
sbatch shells_full_theta_vary/file_10.sh
sbatch shells_full_theta_vary/file_11.sh
sbatch shells_full_theta_vary/file_12.sh
sbatch shells_full_theta_vary/file_13.sh
sbatch shells_full_theta_vary/file_14.sh
sbatch shells_full_theta_vary/file_15.sh
sbatch shells_full_theta_vary/file_16.sh
sbatch shells_full_theta_vary/file_17.sh
sbatch shells_full_theta_vary/file_18.sh
sbatch shells_full_theta_vary/file_19.sh
sbatch shells_full_theta_vary/file_20.sh
