TTree layer_tree("t_layers_energy","tree with energy deposited by 1GeV muon by layer");
Float_t tree_energy[28] = {};
int fill_error = 0;
    
TBranch *b_layer_0 = layer_tree.Branch("layer_0",&tree_energy[0]);
TBranch *b_layer_1 = layer_tree.Branch("layer_1",&tree_energy[1]);
TBranch *b_layer_2 = layer_tree.Branch("layer_2",&tree_energy[2]);
TBranch *b_layer_3 = layer_tree.Branch("layer_3",&tree_energy[3]);
TBranch *b_layer_4 = layer_tree.Branch("layer_4",&tree_energy[4]);
TBranch *b_layer_5 = layer_tree.Branch("layer_5",&tree_energy[5]);
TBranch *b_layer_6 = layer_tree.Branch("layer_6",&tree_energy[6]);
TBranch *b_layer_7 = layer_tree.Branch("layer_7",&tree_energy[7]);
TBranch *b_layer_8 = layer_tree.Branch("layer_8",&tree_energy[8]);
TBranch *b_layer_9 = layer_tree.Branch("layer_9",&tree_energy[9]);
TBranch *b_layer_10 = layer_tree.Branch("layer_10",&tree_energy[10]);
TBranch *b_layer_11 = layer_tree.Branch("layer_11",&tree_energy[11]);
TBranch *b_layer_12 = layer_tree.Branch("layer_12",&tree_energy[12]);
TBranch *b_layer_13 = layer_tree.Branch("layer_13",&tree_energy[13]);
TBranch *b_layer_14 = layer_tree.Branch("layer_14",&tree_energy[14]);
TBranch *b_layer_15 = layer_tree.Branch("layer_15",&tree_energy[15]);
TBranch *b_layer_16 = layer_tree.Branch("layer_16",&tree_energy[16]);
TBranch *b_layer_17 = layer_tree.Branch("layer_17",&tree_energy[17]);
TBranch *b_layer_18 = layer_tree.Branch("layer_18",&tree_energy[18]);
TBranch *b_layer_19 = layer_tree.Branch("layer_19",&tree_energy[19]);
TBranch *b_layer_20 = layer_tree.Branch("layer_20",&tree_energy[20]);
TBranch *b_layer_21 = layer_tree.Branch("layer_21",&tree_energy[21]);
TBranch *b_layer_22 = layer_tree.Branch("layer_22",&tree_energy[22]);
TBranch *b_layer_23 = layer_tree.Branch("layer_23",&tree_energy[23]);
TBranch *b_layer_24 = layer_tree.Branch("layer_24",&tree_energy[24]);
TBranch *b_layer_25 = layer_tree.Branch("layer_25",&tree_energy[25]);
TBranch *b_layer_26 = layer_tree.Branch("layer_26",&tree_energy[26]);
TBranch *b_layer_27 = layer_tree.Branch("layer_27",&tree_energy[27]);

TBranch *b_layer_arr[28] = {b_layer_0,b_layer_1,b_layer_2,b_layer_3,b_layer_4,b_layer_5,b_layer_6,b_layer_7,b_layer_8,b_layer_9,b_layer_10,b_layer_11,b_layer_12,b_layer_13,b_layer_14,b_layer_15,b_layer_16,b_layer_17,b_layer_18,b_layer_19,b_layer_20,b_layer_21,b_layer_22,b_layer_23,b_layer_24,b_layer_25,b_layer_26,b_layer_27};
